name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Read .env
      id: hugo-version
      run: |
        . ./.env
        echo "::set-output name=HUGO_VERSION::${HUGO_VERSION}"

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
        extended: true

    - name: Build
      run: hugo --minify

    - name: CNAME
      run: |
        echo 'herbnsol.life' > ./public/CNAME
    
    # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-how-to-add-cname
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: herbnsol-co/herbnsol-co.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
        SCRIPT_MODE: true
      with:
        emptyCommits: false
        forceOrphan: true
        username: "JoeMatt"
        useremail: "mail@joemattiello.com"
        # commitMessage: ${{ github.event.head_commit.message }}
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
